### ISSUE TITLE
Module parse failed: Unexpected character '#'

### ISSUE THREAD

**Issue by immiao** [immiao/cesium-weather#1]
I'm trying to build up a React + Webpack basic Cesium application. However I got the following error when running `webpack`. Is there any good ideas to resolve this?

```
WARNING in ./node_modules/cesium/index.js
11:35-42 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/cesium/index.js
 @ ./src/App.js
 @ ./index.js

ERROR in ./node_modules/requirejs/bin/r.js
Module parse failed: Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type.
| #!/usr/bin/env node
| /**
|  * @license r.js 2.3.5 Copyright jQuery Foundation and other contributors.
 @ ./node_modules/cesium/index.js 5:16-36
 @ ./src/App.js
 @ ./index.js
```

Here's my code:

```
import Cesium from 'cesium';
...
var viewer = new Cesium.Viewer('cesiumContainer');
```

**Comment by immiao** [comment]
Resolved:

[https://cesiumjs.org/forum/#!msg/cesium-dev/d69RrgOVu9c/RfCoBqrTBAAJ](https://cesiumjs.org/forum/#!msg/cesium-dev/d69RrgOVu9c/RfCoBqrTBAAJ)
[http://blog.isquaredsoftware.com/2017/03/declarative-earth-part-1-cesium-webpack/](http://blog.isquaredsoftware.com/2017/03/declarative-earth-part-1-cesium-webpack/)

**Comment by immiao** [comment]
Well, I followed the instruction but still got an error. My code structure is slightly different from the instruction. What could be the reason?

```
bundle.js:168429 Error constructing CesiumWidget.
Visit <a href="http://get.webgl.org">http://get.webgl.org</a> to verify that your web browser and hardware support WebGL.  Consider trying a different web browser or updating your video drivers.  Detailed error information is below:
Error: Cannot find module "."
Error: Cannot find module "."
    at webpackMissingModule (bundle.js:29861)
    at buildModuleUrl (bundle.js:29861)
    at new Globe (bundle.js:168694)
    at new CesiumWidget (bundle.js:168075)
    at new Viewer (bundle.js:103299)
    at App.componentDidMount (bundle.js:102847)
    at commitLifeCycles (bundle.js:96015)
    at commitAllLifeCycles (bundle.js:97191)
    at HTMLUnknownElement.callCallback (bundle.js:87787)
    at Object.invokeGuardedCallbackDev (bundle.js:87826)
```

My `$PROJECT/index.js`:
```
import React from 'react';
import ReactDOM from 'react-dom';
import App from './src/App';
import './node_modules/bootstrap/dist/css/bootstrap.min.css';
import "cesium/Source/Widgets/widgets.css";
import buildModuleUrl from "cesium/Source/Core/buildModuleUrl";

buildModuleUrl.setBaseUrl('./cesium/');
console.log(buildModuleUrl)

ReactDOM.render(<App />, document.getElementById('container'));
```

My `$PROJECT/src/app.js`:
```
import React, { Component } from 'react';
import Viewer from "cesium/Source/Widgets/Viewer/Viewer";

class App extends Component {
  componentDidMount() {
    var viewer = new Viewer(this.cesiumContainer);
  }

  render() {
    return (
      <div className="App">
        <div className="col-sm-9">
          <div id="cesiumContainer" ref={ element => this.cesiumContainer = element }/>
        </div>
        <div className="col-sm-3">
          Hello
        </div>
      </div>
    );
  }
}

export default App;
```

**Comment by markerikson** [comment]
Perhaps try removing the `.` from the module URL call?  Like: `buildModuleUrl.setBaseUrl('cesium/');`

**Comment by immiao** [comment]
I just tried that. But it doesn't work and gives the same error.

**Comment by markerikson** [comment]
Hmm.  My next suggestion would be to try following the new Webpack setup instructions in the Cesium docs:  https://cesiumjs.org/tutorials/cesium-and-webpack/

**Comment by immiao** [comment]
Thanks a lot for the tutorial! 

After I put

```
    amd: {
        // Enable webpack-friendly use of require in Cesium
        toUrlUndefined: true
    },
```
in my `webpack.config.js`, it works.

**Comment by immiao** [comment]
But how does this work? I search around the Webpack documentation but can't find any information. Did Cesium team contribute this special thing to Webpack?

**Comment by markerikson** [comment]
Looks like it's a use of this particular Webpack config option: https://webpack.js.org/configuration/other-options/#amd

In combination with this change to Cesium's code to look for that special value:

https://github.com/AnalyticalGraphicsInc/cesium/pull/5861/commits/9aa2dff707d8073ec278bb9f1addee3e9b4b3bf7#diff-1f2d871223708f3eeff38a7821941b90

**Comment by immiao** [comment]
Thanks a lot!!
